// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat_settings.sql

package queries

import (
	"context"
)

const deleteChatSetting = `-- name: DeleteChatSetting :exec
DELETE FROM chat_settings WHERE chat_id = ? AND key = ?
`

type DeleteChatSettingParams struct {
	ChatID int64
	Key    string
}

func (q *Queries) DeleteChatSetting(ctx context.Context, arg DeleteChatSettingParams) error {
	_, err := q.db.ExecContext(ctx, deleteChatSetting, arg.ChatID, arg.Key)
	return err
}

const getChatSetting = `-- name: GetChatSetting :one
SELECT value FROM chat_settings WHERE chat_id = ? AND key = ?
`

type GetChatSettingParams struct {
	ChatID int64
	Key    string
}

func (q *Queries) GetChatSetting(ctx context.Context, arg GetChatSettingParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getChatSetting, arg.ChatID, arg.Key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const upsertChatSetting = `-- name: UpsertChatSetting :exec
INSERT INTO chat_settings (chat_id, key, value)
VALUES (?, ?, ?)
ON CONFLICT (chat_id, key) DO UPDATE SET value = excluded.value, updated_at = CURRENT_TIMESTAMP
`

type UpsertChatSettingParams struct {
	ChatID int64
	Key    string
	Value  string
}

func (q *Queries) UpsertChatSetting(ctx context.Context, arg UpsertChatSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertChatSetting, arg.ChatID, arg.Key, arg.Value)
	return err
}
