// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversations.sql

package queries

import (
	"context"
	"database/sql"
)

const getThreadChain = `-- name: GetThreadChain :many
WITH RECURSIVE chain AS (
    SELECT cm.id, cm.thread_root_id, cm.msg_id, cm.parent_msg_id, cm.role, cm.content, cm.created_at
    FROM conversation_messages cm
    WHERE cm.msg_id = ?2
    UNION ALL
    SELECT cm2.id, cm2.thread_root_id, cm2.msg_id, cm2.parent_msg_id, cm2.role, cm2.content, cm2.created_at
    FROM conversation_messages cm2
    INNER JOIN chain c ON cm2.msg_id = c.parent_msg_id
)
SELECT chain.role, chain.content FROM chain
ORDER BY chain.id ASC
LIMIT ?1
`

type GetThreadChainParams struct {
	MaxMessages int64
	LeafMsgID   int64
}

type GetThreadChainRow struct {
	Role    string
	Content string
}

func (q *Queries) GetThreadChain(ctx context.Context, arg GetThreadChainParams) ([]GetThreadChainRow, error) {
	rows, err := q.db.QueryContext(ctx, getThreadChain, arg.MaxMessages, arg.LeafMsgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetThreadChainRow
	for rows.Next() {
		var i GetThreadChainRow
		if err := rows.Scan(&i.Role, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertConversationMessage = `-- name: InsertConversationMessage :exec
INSERT INTO conversation_messages (thread_root_id, msg_id, parent_msg_id, role, content)
VALUES (?, ?, ?, ?, ?)
`

type InsertConversationMessageParams struct {
	ThreadRootID int64
	MsgID        int64
	ParentMsgID  sql.NullInt64
	Role         string
	Content      string
}

func (q *Queries) InsertConversationMessage(ctx context.Context, arg InsertConversationMessageParams) error {
	_, err := q.db.ExecContext(ctx, insertConversationMessage,
		arg.ThreadRootID,
		arg.MsgID,
		arg.ParentMsgID,
		arg.Role,
		arg.Content,
	)
	return err
}

const isConversationMessage = `-- name: IsConversationMessage :one
SELECT thread_root_id FROM conversation_messages WHERE msg_id = ?
`

func (q *Queries) IsConversationMessage(ctx context.Context, msgID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, isConversationMessage, msgID)
	var thread_root_id int64
	err := row.Scan(&thread_root_id)
	return thread_root_id, err
}
