// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: filter_triggers.sql

package queries

import (
	"context"
)

const checkDuplicateTriggerInChat = `-- name: CheckDuplicateTriggerInChat :one
SELECT EXISTS(
    SELECT 1
    FROM filter_triggers ft
    JOIN filters f ON ft.filter_id = f.id
    WHERE f.chat_id = ?1 AND ft.trigger_text = ?2
) AS has_duplicate
`

type CheckDuplicateTriggerInChatParams struct {
	ChatID      int64
	TriggerText string
}

func (q *Queries) CheckDuplicateTriggerInChat(ctx context.Context, arg CheckDuplicateTriggerInChatParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkDuplicateTriggerInChat, arg.ChatID, arg.TriggerText)
	var has_duplicate int64
	err := row.Scan(&has_duplicate)
	return has_duplicate, err
}

const countTriggersByFilterID = `-- name: CountTriggersByFilterID :one
SELECT COUNT(*) FROM filter_triggers
WHERE filter_id = ?1
`

func (q *Queries) CountTriggersByFilterID(ctx context.Context, filterID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTriggersByFilterID, filterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteTriggerByChatAndText = `-- name: DeleteTriggerByChatAndText :one
DELETE FROM filter_triggers
WHERE id IN (
    SELECT ft.id
    FROM filter_triggers ft
    JOIN filters f ON ft.filter_id = f.id
    WHERE f.chat_id = ?1 AND ft.trigger_text = ?2
    LIMIT 1
)
RETURNING filter_id
`

type DeleteTriggerByChatAndTextParams struct {
	ChatID      int64
	TriggerText string
}

func (q *Queries) DeleteTriggerByChatAndText(ctx context.Context, arg DeleteTriggerByChatAndTextParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, deleteTriggerByChatAndText, arg.ChatID, arg.TriggerText)
	var filter_id int64
	err := row.Scan(&filter_id)
	return filter_id, err
}

const getTriggersByFilterID = `-- name: GetTriggersByFilterID :many
SELECT id, filter_id, trigger_text
FROM filter_triggers
WHERE filter_id = ?1
ORDER BY id
`

func (q *Queries) GetTriggersByFilterID(ctx context.Context, filterID int64) ([]FilterTrigger, error) {
	rows, err := q.db.QueryContext(ctx, getTriggersByFilterID, filterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FilterTrigger
	for rows.Next() {
		var i FilterTrigger
		if err := rows.Scan(&i.ID, &i.FilterID, &i.TriggerText); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertFilterTrigger = `-- name: InsertFilterTrigger :exec
INSERT INTO filter_triggers (filter_id, trigger_text)
VALUES (?1, ?2)
`

type InsertFilterTriggerParams struct {
	FilterID    int64
	TriggerText string
}

func (q *Queries) InsertFilterTrigger(ctx context.Context, arg InsertFilterTriggerParams) error {
	_, err := q.db.ExecContext(ctx, insertFilterTrigger, arg.FilterID, arg.TriggerText)
	return err
}
