// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: filter_text_resp.sql

package queries

import (
	"context"
)

const getTextResponseByFilterID = `-- name: GetTextResponseByFilterID :one
SELECT filter_id, response_text
FROM filter_text_resp
WHERE filter_id = ?1
`

func (q *Queries) GetTextResponseByFilterID(ctx context.Context, filterID int64) (FilterTextResp, error) {
	row := q.db.QueryRowContext(ctx, getTextResponseByFilterID, filterID)
	var i FilterTextResp
	err := row.Scan(&i.FilterID, &i.ResponseText)
	return i, err
}

const insertTextResponse = `-- name: InsertTextResponse :exec
INSERT INTO filter_text_resp (filter_id, response_text)
VALUES (?1, ?2)
`

type InsertTextResponseParams struct {
	FilterID     int64
	ResponseText string
}

func (q *Queries) InsertTextResponse(ctx context.Context, arg InsertTextResponseParams) error {
	_, err := q.db.ExecContext(ctx, insertTextResponse, arg.FilterID, arg.ResponseText)
	return err
}
