// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: filter_media_resp.sql

package queries

import (
	"context"
)

const countMediaResponsesByHash = `-- name: CountMediaResponsesByHash :one
SELECT COUNT(*) FROM filter_media_resp
WHERE media_hash = ?1
`

func (q *Queries) CountMediaResponsesByHash(ctx context.Context, mediaHash string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMediaResponsesByHash, mediaHash)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getMediaHashesByChatID = `-- name: GetMediaHashesByChatID :many
SELECT DISTINCT media_hash
FROM filter_media_resp
WHERE filter_id IN (
    SELECT id FROM filters WHERE chat_id = ?1
)
`

func (q *Queries) GetMediaHashesByChatID(ctx context.Context, chatID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getMediaHashesByChatID, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var media_hash string
		if err := rows.Scan(&media_hash); err != nil {
			return nil, err
		}
		items = append(items, media_hash)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMediaResponseByFilterID = `-- name: GetMediaResponseByFilterID :one
SELECT filter_id, media_hash, media_type
FROM filter_media_resp
WHERE filter_id = ?1
`

func (q *Queries) GetMediaResponseByFilterID(ctx context.Context, filterID int64) (FilterMediaResp, error) {
	row := q.db.QueryRowContext(ctx, getMediaResponseByFilterID, filterID)
	var i FilterMediaResp
	err := row.Scan(&i.FilterID, &i.MediaHash, &i.MediaType)
	return i, err
}

const insertMediaResponse = `-- name: InsertMediaResponse :exec
INSERT INTO filter_media_resp (filter_id, media_hash, media_type)
VALUES (?1, ?2, ?3)
`

type InsertMediaResponseParams struct {
	FilterID  int64
	MediaHash string
	MediaType string
}

func (q *Queries) InsertMediaResponse(ctx context.Context, arg InsertMediaResponseParams) error {
	_, err := q.db.ExecContext(ctx, insertMediaResponse, arg.FilterID, arg.MediaHash, arg.MediaType)
	return err
}
