// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: filter_reaction_resp.sql

package queries

import (
	"context"
)

const getReactionResponseByFilterID = `-- name: GetReactionResponseByFilterID :one
SELECT filter_id, reaction
FROM filter_reaction_resp
WHERE filter_id = ?1
`

func (q *Queries) GetReactionResponseByFilterID(ctx context.Context, filterID int64) (FilterReactionResp, error) {
	row := q.db.QueryRowContext(ctx, getReactionResponseByFilterID, filterID)
	var i FilterReactionResp
	err := row.Scan(&i.FilterID, &i.Reaction)
	return i, err
}

const insertReactionResponse = `-- name: InsertReactionResponse :exec
INSERT INTO filter_reaction_resp (filter_id, reaction)
VALUES (?1, ?2)
`

type InsertReactionResponseParams struct {
	FilterID int64
	Reaction string
}

func (q *Queries) InsertReactionResponse(ctx context.Context, arg InsertReactionResponseParams) error {
	_, err := q.db.ExecContext(ctx, insertReactionResponse, arg.FilterID, arg.Reaction)
	return err
}
