// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: filters.sql

package queries

import (
	"context"
)

const deleteFilter = `-- name: DeleteFilter :exec
DELETE FROM filters WHERE id = ?1
`

func (q *Queries) DeleteFilter(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteFilter, id)
	return err
}

const getFilterByID = `-- name: GetFilterByID :one
SELECT id, chat_id, response_type, created_at
FROM filters
WHERE id = ?1
`

func (q *Queries) GetFilterByID(ctx context.Context, id int64) (Filter, error) {
	row := q.db.QueryRowContext(ctx, getFilterByID, id)
	var i Filter
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.ResponseType,
		&i.CreatedAt,
	)
	return i, err
}

const insertFilter = `-- name: InsertFilter :one
INSERT INTO filters (chat_id, response_type)
VALUES (?1, ?2)
RETURNING id
`

type InsertFilterParams struct {
	ChatID       int64
	ResponseType string
}

func (q *Queries) InsertFilter(ctx context.Context, arg InsertFilterParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertFilter, arg.ChatID, arg.ResponseType)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listFiltersByChatID = `-- name: ListFiltersByChatID :many
SELECT id, chat_id, response_type, created_at
FROM filters
WHERE chat_id = ?1
ORDER BY created_at DESC
`

func (q *Queries) ListFiltersByChatID(ctx context.Context, chatID int64) ([]Filter, error) {
	rows, err := q.db.QueryContext(ctx, listFiltersByChatID, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Filter
	for rows.Next() {
		var i Filter
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.ResponseType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
