// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: filter_matching.sql

package queries

import (
	"context"
	"database/sql"
)

const findMatchingFilters = `-- name: FindMatchingFilters :many
WITH matched AS (
    SELECT f.id, f.response_type
    FROM filter_triggers t
    JOIN filters f ON t.filter_id = f.id
    WHERE f.chat_id = ?1
    AND INSTR(' ' || ?2 || ' ', ' ' || t.trigger_text || ' ') > 0
)
SELECT m.id, m.response_type, COALESCE(ft.response_text, '') AS response_text,
       COALESCE(fm.media_hash, '') AS media_hash, COALESCE(fm.media_type, '') AS media_type, 
       COALESCE(fr.reaction, '') AS reaction
FROM matched m
LEFT JOIN filter_text_resp ft ON m.id = ft.filter_id
LEFT JOIN filter_media_resp fm ON m.id = fm.filter_id
LEFT JOIN filter_reaction_resp fr ON m.id = fr.filter_id
`

type FindMatchingFiltersParams struct {
	ChatID  int64
	Column2 sql.NullString
}

type FindMatchingFiltersRow struct {
	ID           int64
	ResponseType string
	ResponseText string
	MediaHash    string
	MediaType    string
	Reaction     string
}

func (q *Queries) FindMatchingFilters(ctx context.Context, arg FindMatchingFiltersParams) ([]FindMatchingFiltersRow, error) {
	rows, err := q.db.QueryContext(ctx, findMatchingFilters, arg.ChatID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindMatchingFiltersRow
	for rows.Next() {
		var i FindMatchingFiltersRow
		if err := rows.Scan(
			&i.ID,
			&i.ResponseType,
			&i.ResponseText,
			&i.MediaHash,
			&i.MediaType,
			&i.Reaction,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
