// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memory_read_tokens.sql

package queries

import (
	"context"
)

const getReadToken = `-- name: GetReadToken :one
WITH RECURSIVE branch(msg_id, parent_msg_id, depth) AS (
    SELECT c.msg_id, c.parent_msg_id, 0
    FROM conversation_messages c
    WHERE c.msg_id = ?          -- current turn's msg_id
    UNION ALL
    SELECT cm.msg_id, cm.parent_msg_id, b.depth + 1
    FROM conversation_messages cm
    JOIN branch b ON cm.msg_id = b.parent_msg_id
)
SELECT t.observed_sha
FROM branch b
JOIN memory_read_tokens t ON t.msg_id = b.msg_id
ORDER BY b.depth ASC
LIMIT 1
`

func (q *Queries) GetReadToken(ctx context.Context, msgID int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getReadToken, msgID)
	var observed_sha string
	err := row.Scan(&observed_sha)
	return observed_sha, err
}

const saveToken = `-- name: SaveToken :exec
INSERT INTO memory_read_tokens (msg_id, observed_sha)
VALUES (?1, ?2)
ON CONFLICT (msg_id) DO UPDATE SET observed_sha = ?2
`

type SaveTokenParams struct {
	MsgID       int64
	ObservedSha string
}

func (q *Queries) SaveToken(ctx context.Context, arg SaveTokenParams) error {
	_, err := q.db.ExecContext(ctx, saveToken, arg.MsgID, arg.ObservedSha)
	return err
}
