// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memory_read_tokens.sql

package queries

import (
	"context"
)

const getReadToken = `-- name: GetReadToken :one
WITH RECURSIVE branch(msg_id, parent_msg_id, depth) AS (
    SELECT
        CAST(?1 AS INTEGER) AS msg_id,
        (SELECT c.parent_msg_id FROM conversation_messages c WHERE c.msg_id = ?1) AS parent_msg_id,
        0 AS depth
    UNION ALL
    SELECT cm.msg_id, cm.parent_msg_id, b.depth + 1
    FROM conversation_messages cm
    JOIN branch b ON cm.msg_id = b.parent_msg_id
)
SELECT t.observed_sha
FROM branch b
JOIN memory_read_tokens t ON t.msg_id = b.msg_id
ORDER BY b.depth ASC
LIMIT 1
`

// Walk up the conversation ancestry from the current msg_id, returning the
// nearest saved read-token. The seed row uses the parameter directly (rather
// than joining conversation_messages) so this also works during the first
// turn of a /prompt, when the current msg_id has not yet been persisted into
// conversation_messages (that insert happens after ChatCompletion returns).
func (q *Queries) GetReadToken(ctx context.Context, dollar_1 int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getReadToken, dollar_1)
	var observed_sha string
	err := row.Scan(&observed_sha)
	return observed_sha, err
}

const saveToken = `-- name: SaveToken :exec
INSERT INTO memory_read_tokens (msg_id, observed_sha)
VALUES (?1, ?2)
ON CONFLICT (msg_id) DO UPDATE SET observed_sha = ?2
`

type SaveTokenParams struct {
	MsgID       int64
	ObservedSha string
}

func (q *Queries) SaveToken(ctx context.Context, arg SaveTokenParams) error {
	_, err := q.db.ExecContext(ctx, saveToken, arg.MsgID, arg.ObservedSha)
	return err
}
