// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql"
	"time"
)

type ConversationMessage struct {
	ID           int64
	ThreadRootID int64
	MsgID        int64
	ParentMsgID  sql.NullInt64
	Role         string
	Content      string
	CreatedAt    time.Time
	SenderName   string
}

type Filter struct {
	ID           int64
	ChatID       int64
	ResponseType string
	CreatedAt    time.Time
}

type FilterMediaResp struct {
	FilterID  int64
	MediaHash string
	MediaType string
}

type FilterReactionResp struct {
	FilterID int64
	Reaction string
}

type FilterTextResp struct {
	FilterID     int64
	ResponseText string
}

type FilterTrigger struct {
	ID          int64
	FilterID    int64
	TriggerText string
}

type SchemaVersion struct {
	ID        int64
	AppliedAt time.Time
}
