// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: schema_version.sql

package queries

import (
	"context"
)

const getSchemaVersion = `-- name: GetSchemaVersion :one
SELECT id, applied_at FROM schema_version ORDER BY id DESC LIMIT 1
`

// Retrieves the current schema version from the database.
func (q *Queries) GetSchemaVersion(ctx context.Context) (SchemaVersion, error) {
	row := q.db.QueryRowContext(ctx, getSchemaVersion)
	var i SchemaVersion
	err := row.Scan(&i.ID, &i.AppliedAt)
	return i, err
}
