services:
  patrizio:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: -f /data/ serve
    volumes:
      - ./data:/data:rw
    logging:
      driver: "json-file"
      options:
        mode: "non-blocking"
        max-size: "10m"
        max-file: "3"
