name: Commit check

on:
  push:
    branches:
      - 'renovate/**'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  go-checks:
    name: Golang related checks
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version-file: 'go.mod'
      - name: Golang-ci lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9
        with:
          version: v2.12.2

      - name: Ensures Go code is formatted
        uses: nickcharlton/diff-check@9fa7ac2bd275b9ec60f13dbcef1b90cfaadc1872 # v1
        with:
          command: gofmt -w .

      - name: Ensures Go mod tidy is up to date
        uses: nickcharlton/diff-check@9fa7ac2bd275b9ec60f13dbcef1b90cfaadc1872 # v1
        with:
          command: go mod tidy

      - name: Go build
        run: go build ./...

      - name: Run tests
        run: make test

  doc-checks:
    name: Docs linting
    runs-on: ubuntu-slim
    steps:
      - name: Clone repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Website linting
        uses: vale-cli/vale-action@v3
        with:
          reporter: github-pr-review
          fail_on_error: true
          fail_level: warning
          glob: 'docs/**/*.md'

  doc-build:
    runs-on: ubuntu-slim
    name: Build public docs
    steps:
      - name: Clone repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Setup Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version-file: ".python-version"

      - name: Setup uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0

      - name: Run make doc-build
        run: make doc-build
