name: Docs compilation

on:
  push:
    branches:
      - 'renovate/**'
  pull_request:
    paths:
      - 'docs/**'
      - 'pyproject.toml'
      - 'uv.lock'
      - '.python-version'
      - 'zensical.toml'
      - '.github/workflows/docs.yml'
      - 'Makefile'

jobs:
  build:
    runs-on: ubuntu-slim
    name: Build docs
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version-file: ".python-version"
      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          version: "latest-known"
      - run: make doc-build
